Repository beyond-sw-camp/be11-2nd-TWINSTAR-BE, pull requests merged in 2025-02, with the labels that each got.

#30 [Feat][chore]user detail list/user_list_fix
  build.gradle
  src/main/java/com/TwinStar/TwinStar/TwinStarApplication.java
  src/main/java/com/TwinStar/TwinStar/admin/controller/AdminController.java
  src/main/java/com/TwinStar/TwinStar/admin/dtos/UserDetailDto.java
  src/main/java/com/TwinStar/TwinStar/admin/dtos/UserListDto.java
  src/main/java/com/TwinStar/TwinStar/admin/repostiory/AdminRepository.java
  src/main/java/com/TwinStar/TwinStar/admin/service/AdminService.java
  src/main/java/com/TwinStar/TwinStar/common/CommonErrorDto.java
  src/main/java/com/TwinStar/TwinStar/commonDomain/IdVisibility.java
  src/main/java/com/TwinStar/TwinStar/commonDomain/Post.java
  src/main/java/com/TwinStar/TwinStar/commonDomain/PostStatus.java
  src/main/java/com/TwinStar/TwinStar/commonDomain/PostVisibility.java
  src/main/java/com/TwinStar/TwinStar/commonDomain/Report.java
  src/main/java/com/TwinStar/TwinStar/commonDomain/ReportStatus.java
  src/main/java/com/TwinStar/TwinStar/commonDomain/Sex.java
  src/main/java/com/TwinStar/TwinStar/commonDomain/Type.java
  src/main/java/com/TwinStar/TwinStar/commonDomain/User.java
  src/main/java/com/TwinStar/TwinStar/commonDomain/UserStatus.java
Labels: Feat, Chore

#37 [feat]user_create #closed 36
  src/main/java/com/TwinStar/TwinStar/common/auth/JwtAuthFilter.java
  src/main/java/com/TwinStar/TwinStar/user/controller/UserController.java
  src/main/java/com/TwinStar/TwinStar/user/domain/User.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserSaveReq.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserUpdateReq.java
  src/main/java/com/TwinStar/TwinStar/user/service/UserService.java
Labels: Feat

#39 close #38 [chore] common domain YN 추가
  src/main/java/com/TwinStar/TwinStar/common/domain/YN.java
Labels: Chore

#40 [feat]doLogin #closed 31
  src/main/java/com/TwinStar/TwinStar/admin/controller/AdminController.java
  src/main/java/com/TwinStar/TwinStar/admin/dtos/UserDetailDto.java
  src/main/java/com/TwinStar/TwinStar/admin/dtos/UserListDto.java
  src/main/java/com/TwinStar/TwinStar/admin/repostiory/AdminRepository.java
  src/main/java/com/TwinStar/TwinStar/admin/service/AdminService.java
  src/main/java/com/TwinStar/TwinStar/alarm/domain/Alarm.java
  src/main/java/com/TwinStar/TwinStar/common/auth/JwtTokenProvider.java
  src/main/java/com/TwinStar/TwinStar/follow/repository/FollowRepository.java
  src/main/java/com/TwinStar/TwinStar/user/controller/UserController.java
  src/main/java/com/TwinStar/TwinStar/user/domain/AdminYn.java
  src/main/java/com/TwinStar/TwinStar/user/domain/User.java
  src/main/java/com/TwinStar/TwinStar/user/dto/LoginDto.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserSaveReq.java
  src/main/java/com/TwinStar/TwinStar/user/service/UserService.java
Labels: Feat

#77 Feat/read merge
  src/main/java/com/TwinStar/TwinStar/post/controller/PostReadController.java
  src/main/java/com/TwinStar/TwinStar/post/dto/HomePostResDto.java
  src/main/java/com/TwinStar/TwinStar/post/dto/ProfilePostResDto.java
  src/main/java/com/TwinStar/TwinStar/post/service/PostReadService.java
  src/main/java/com/TwinStar/TwinStar/user/service/UserService.java
Labels: Feat

#80 Feat/follow
  src/main/java/com/TwinStar/TwinStar/comment/domain/Comment.java
  src/main/java/com/TwinStar/TwinStar/follow/controller/FollowController.java
  src/main/java/com/TwinStar/TwinStar/follow/domain/Follow.java
  src/main/java/com/TwinStar/TwinStar/follow/dto/FollowDto.java
  src/main/java/com/TwinStar/TwinStar/follow/dto/FollowReq.java
  src/main/java/com/TwinStar/TwinStar/follow/repository/FollowRepository.java
  src/main/java/com/TwinStar/TwinStar/follow/service/FollowService.java
  src/main/java/com/TwinStar/TwinStar/user/domain/User.java
Labels: Feat

#86 [feat] 댓글 폴더링 및 댓글,게시물쪽 entity추가
  src/main/java/com/TwinStar/TwinStar/comment/controller/CommentController.java
  src/main/java/com/TwinStar/TwinStar/comment/controller/CommentReadController.java
  src/main/java/com/TwinStar/TwinStar/comment/controller/CommentWriteController.java
  src/main/java/com/TwinStar/TwinStar/comment/domain/Comment.java
  src/main/java/com/TwinStar/TwinStar/comment/domain/CommentLike.java
  src/main/java/com/TwinStar/TwinStar/comment/service/CommentReadService.java
  src/main/java/com/TwinStar/TwinStar/comment/service/CommentService.java
  src/main/java/com/TwinStar/TwinStar/comment/service/CommentWriteService.java
  src/main/java/com/TwinStar/TwinStar/common/domain/Visibility.java
  src/main/java/com/TwinStar/TwinStar/post/domain/Post.java
  src/main/java/com/TwinStar/TwinStar/post/domain/PostFile.java
  src/main/java/com/TwinStar/TwinStar/post/domain/PostLike.java
  src/main/java/com/TwinStar/TwinStar/post/domain/PostVisibility.java
  src/main/java/com/TwinStar/TwinStar/post/dto/PostCreateReqDto.java
  src/main/java/com/TwinStar/TwinStar/post/dto/PostUpdateReqDto.java
  src/main/java/com/TwinStar/TwinStar/user/domain/User.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserListDto.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserProfileUpdateDto.java
Labels: Feat

#88 [feat]관리자 권한 회수, 부여 및 특정 사용자 정지
  src/main/java/com/TwinStar/TwinStar/comment/controller/CommentReadController.java
  src/main/java/com/TwinStar/TwinStar/follow/repository/FollowRepository.java
  src/main/java/com/TwinStar/TwinStar/post/domain/Post.java
  src/main/java/com/TwinStar/TwinStar/post/domain/PostFile.java
  src/main/java/com/TwinStar/TwinStar/report/controller/ReportController.java
  src/main/java/com/TwinStar/TwinStar/user/controller/UserController.java
  src/main/java/com/TwinStar/TwinStar/user/domain/IdVisibility.java
  src/main/java/com/TwinStar/TwinStar/user/domain/User.java
  src/main/java/com/TwinStar/TwinStar/user/dto/ChangeIdVisibility.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserListDto.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserProfileDto.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserProfileUpdateDto.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserSaveReq.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserUpdateReq.java
  src/main/java/com/TwinStar/TwinStar/user/repository/UserRepository.java
  src/main/java/com/TwinStar/TwinStar/user/service/UserBanScheduler.java
  src/main/java/com/TwinStar/TwinStar/user/service/UserService.java
Labels: Feat

#87 Update Visibility.java
  src/main/java/com/TwinStar/TwinStar/common/domain/Visibility.java
Labels: Chore

#109 Feat/chat 채팅개발
  build.gradle
  src/main/java/com/TwinStar/TwinStar/chat/config/StompEventListener.java
  src/main/java/com/TwinStar/TwinStar/chat/config/StompHandler.java
  src/main/java/com/TwinStar/TwinStar/chat/config/StompWebSocketConfig.java
  src/main/java/com/TwinStar/TwinStar/chat/controller/ChatController.java
  src/main/java/com/TwinStar/TwinStar/chat/controller/StompController.java
  src/main/java/com/TwinStar/TwinStar/chat/domain/Chat.java
  src/main/java/com/TwinStar/TwinStar/chat/domain/ChatMessage.java
  src/main/java/com/TwinStar/TwinStar/chat/domain/ChatParticipant.java
  src/main/java/com/TwinStar/TwinStar/chat/domain/ChatRoom.java
  src/main/java/com/TwinStar/TwinStar/chat/domain/ReadStatus.java
  src/main/java/com/TwinStar/TwinStar/chat/dto/ChatMessageDto.java
  src/main/java/com/TwinStar/TwinStar/chat/dto/ChatRoomCreateReqDto.java
  src/main/java/com/TwinStar/TwinStar/chat/dto/ChatRoomResDto.java
  src/main/java/com/TwinStar/TwinStar/chat/repository/ChatMessageRepository.java
  src/main/java/com/TwinStar/TwinStar/chat/repository/ChatParticipantRepository.java
  src/main/java/com/TwinStar/TwinStar/chat/repository/ChatRepository.java
  src/main/java/com/TwinStar/TwinStar/chat/repository/ChatRoomRepository.java
  src/main/java/com/TwinStar/TwinStar/chat/repository/ReadStatusRepository.java
  src/main/java/com/TwinStar/TwinStar/chat/service/ChatService.java
  src/main/java/com/TwinStar/TwinStar/chat/service/RedisPubSubService.java
  src/main/java/com/TwinStar/TwinStar/common/auth/JwtTokenProvider.java
  src/main/java/com/TwinStar/TwinStar/common/config/RedisConfig.java
  src/main/java/com/TwinStar/TwinStar/common/config/SecurityConfig.java
  src/main/java/com/TwinStar/TwinStar/user/controller/UserController.java
  src/main/java/com/TwinStar/TwinStar/user/repository/UserRepository.java
Labels: Feat

#110 Fix/신고목록조회 및 상세목록조회
  src/main/java/com/TwinStar/TwinStar/blackList/domain/BlackList.java
  src/main/java/com/TwinStar/TwinStar/blackList/dto/BlockRequest.java
  src/main/java/com/TwinStar/TwinStar/blackList/repository/BlackListRepository.java
  src/main/java/com/TwinStar/TwinStar/common/config/SchedulingConfig.java
  src/main/java/com/TwinStar/TwinStar/report/controller/ReportController.java
  src/main/java/com/TwinStar/TwinStar/report/domain/Report.java
  src/main/java/com/TwinStar/TwinStar/report/dtos/ReportProcessRequestDto.java
  src/main/java/com/TwinStar/TwinStar/report/dtos/ReportProcessResponseDto.java
  src/main/java/com/TwinStar/TwinStar/report/dtos/ReportRequestDto.java
  src/main/java/com/TwinStar/TwinStar/report/dtos/ReportResponseDto.java
  src/main/java/com/TwinStar/TwinStar/report/service/ReportService.java
  src/main/java/com/TwinStar/TwinStar/user/controller/UserController.java
  src/main/java/com/TwinStar/TwinStar/user/domain/User.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserDetailDto.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserListDto.java
  src/main/java/com/TwinStar/TwinStar/user/service/UserService.java
Labels: Chore

#112 fix/search 유저목록 검색 기능 성공
  src/main/java/com/TwinStar/TwinStar/user/controller/UserController.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserSearchDto.java
  src/main/java/com/TwinStar/TwinStar/user/service/UserService.java
Labels: Chore

#113 Feat/chat 채팅 기능 구현 완료
  build.gradle
  src/main/java/com/TwinStar/TwinStar/chat/controller/ChatController.java
  src/main/java/com/TwinStar/TwinStar/chat/controller/StompController.java
  src/main/java/com/TwinStar/TwinStar/chat/domain/ChatParticipant.java
  src/main/java/com/TwinStar/TwinStar/chat/domain/ChatRoom.java
  src/main/java/com/TwinStar/TwinStar/chat/dto/ChatMessageDto.java
  src/main/java/com/TwinStar/TwinStar/chat/dto/ChatRoomResDto.java
  src/main/java/com/TwinStar/TwinStar/chat/repository/ChatMessageRepository.java
  src/main/java/com/TwinStar/TwinStar/chat/repository/ChatParticipantRepository.java
  src/main/java/com/TwinStar/TwinStar/chat/repository/ChatRoomRepository.java
  src/main/java/com/TwinStar/TwinStar/chat/service/ChatService.java
  src/main/java/com/TwinStar/TwinStar/chat/service/RedisPubSubService.java
  src/main/java/com/TwinStar/TwinStar/common/config/JacksonConfig.java
  src/main/java/com/TwinStar/TwinStar/user/controller/UserController.java
Labels: Feat

#121 post, postLike, comment, commentLike fix2
  src/main/java/com/TwinStar/TwinStar/post/controller/PostController.java
  src/main/java/com/TwinStar/TwinStar/post/dto/PostCreateReqDto.java
Labels: Feat

#122 [feat] aws 파일저장 인코딩 기능 추가
  src/main/java/com/TwinStar/TwinStar/post/service/PostService.java
Labels: Feat

#124 Feat/comment
  src/main/java/com/TwinStar/TwinStar/comment/controller/CommentController.java
  src/main/java/com/TwinStar/TwinStar/comment/domain/Comment.java
  src/main/java/com/TwinStar/TwinStar/comment/dto/CommentCreateReqDto.java
  src/main/java/com/TwinStar/TwinStar/comment/dto/CommentUpdateReqDto.java
  src/main/java/com/TwinStar/TwinStar/comment/dto/ReplyCommentCreateReqDto.java
  src/main/java/com/TwinStar/TwinStar/comment/repository/CommentRepository.java
  src/main/java/com/TwinStar/TwinStar/comment/service/CommentService.java
  src/main/java/com/TwinStar/TwinStar/post/controller/PostController.java
Labels: Feat

#127 Feat/alarm
  src/main/java/com/TwinStar/TwinStar/alarm/controller/AlarmController.java
  src/main/java/com/TwinStar/TwinStar/alarm/domain/Alarm.java
  src/main/java/com/TwinStar/TwinStar/alarm/dto/AlarmCommonResDto.java
  src/main/java/com/TwinStar/TwinStar/alarm/dto/AlarmResDto.java
  src/main/java/com/TwinStar/TwinStar/alarm/repository/AlarmRepository.java
  src/main/java/com/TwinStar/TwinStar/alarm/service/AlarmService.java
  src/main/java/com/TwinStar/TwinStar/chat/dto/ChatMessageDto.java
  src/main/java/com/TwinStar/TwinStar/comment/service/CommentService.java
Labels: Feat

#128 Feat/alarm
  src/main/java/com/TwinStar/TwinStar/alarm/domain/Alarm.java
  src/main/java/com/TwinStar/TwinStar/alarm/repository/AlarmRepository.java
  src/main/java/com/TwinStar/TwinStar/comment/controller/CommentController.java
  src/main/java/com/TwinStar/TwinStar/comment/domain/Comment.java
  src/main/java/com/TwinStar/TwinStar/comment/dto/CommentLikeResDto.java
  src/main/java/com/TwinStar/TwinStar/comment/repository/CommentLikeRepository.java
  src/main/java/com/TwinStar/TwinStar/comment/service/CommentLikeService.java
  src/main/java/com/TwinStar/TwinStar/comment/service/CommentService.java
  src/main/java/com/TwinStar/TwinStar/common/config/RedisConfig.java
  src/main/java/com/TwinStar/TwinStar/follow/service/FollowService.java
  src/main/java/com/TwinStar/TwinStar/post/controller/PostController.java
  src/main/java/com/TwinStar/TwinStar/post/dto/LikeRabbitDto.java
  src/main/java/com/TwinStar/TwinStar/post/dto/PostLikeResDto.java
  src/main/java/com/TwinStar/TwinStar/post/repository/PostLikeRepository.java
  src/main/java/com/TwinStar/TwinStar/post/service/LikeEventListener.java
  src/main/java/com/TwinStar/TwinStar/post/service/LikeService.java
  src/main/java/com/TwinStar/TwinStar/post/service/PostLikeService.java
  src/main/java/com/TwinStar/TwinStar/post/service/PostService.java
Labels: Feat

#129 Feat/postList
  src/main/java/com/TwinStar/TwinStar/follow/repository/FollowRepository.java
  src/main/java/com/TwinStar/TwinStar/post/controller/PostController.java
  src/main/java/com/TwinStar/TwinStar/post/dto/CommentListResDto.java
  src/main/java/com/TwinStar/TwinStar/post/dto/PostDetailResDto.java
  src/main/java/com/TwinStar/TwinStar/post/dto/PostListResDto.java
  src/main/java/com/TwinStar/TwinStar/post/repository/PostRepository.java
  src/main/java/com/TwinStar/TwinStar/post/service/PostService.java
Labels: Feat

#130 Feat/post
  src/main/java/com/TwinStar/TwinStar/comment/repository/CommentLikeRepository.java
  src/main/java/com/TwinStar/TwinStar/comment/repository/CommentRepository.java
  src/main/java/com/TwinStar/TwinStar/post/controller/PostController.java
  src/main/java/com/TwinStar/TwinStar/post/dto/CommentListResDto.java
  src/main/java/com/TwinStar/TwinStar/post/dto/PostDetailResDto.java
  src/main/java/com/TwinStar/TwinStar/post/dto/PostListResDto.java
  src/main/java/com/TwinStar/TwinStar/post/repository/PostLikeRepository.java
  src/main/java/com/TwinStar/TwinStar/post/repository/PostRepository.java
  src/main/java/com/TwinStar/TwinStar/post/service/PostService.java
Labels: Feat

#131 [feat] CommentListResDto 필드 추가
  src/main/java/com/TwinStar/TwinStar/post/dto/CommentListResDto.java
Labels: Feat

#132 Feat/like
  src/main/java/com/TwinStar/TwinStar/alarm/service/AlarmService.java
  src/main/java/com/TwinStar/TwinStar/follow/controller/FollowController.java
  src/main/java/com/TwinStar/TwinStar/follow/repository/FollowRepository.java
  src/main/java/com/TwinStar/TwinStar/follow/service/FollowService.java
  src/main/java/com/TwinStar/TwinStar/post/controller/PostController.java
  src/main/java/com/TwinStar/TwinStar/post/dto/PostDetailResDto.java
  src/main/java/com/TwinStar/TwinStar/post/dto/PostListResDto.java
  src/main/java/com/TwinStar/TwinStar/post/repository/PostLikeRepository.java
  src/main/java/com/TwinStar/TwinStar/post/repository/PostRepository.java
  src/main/java/com/TwinStar/TwinStar/post/service/PostService.java
  src/main/java/com/TwinStar/TwinStar/user/dto/UserListResDto.java
Labels: Feat

#133 Feat/commentLike
  src/main/java/com/TwinStar/TwinStar/comment/controller/CommentController.java
  src/main/java/com/TwinStar/TwinStar/comment/repository/CommentLikeRepository.java
  src/main/java/com/TwinStar/TwinStar/comment/service/CommentLikeService.java
Labels: Feat

#134 Feat/alarm
  src/main/java/com/TwinStar/TwinStar/alarm/dto/AlarmResDto.java
  src/main/java/com/TwinStar/TwinStar/alarm/service/AlarmService.java
  src/main/java/com/TwinStar/TwinStar/post/controller/PostController.java
Labels: Chore

#135 [refactor] 링크 주소 수정
  src/main/java/com/TwinStar/TwinStar/alarm/controller/SseController.java
  src/main/java/com/TwinStar/TwinStar/follow/service/FollowService.java
Labels: Refactor
